### ISSUE TITLE
Warehouses not accepting imports

### ISSUE THREAD

**Issue by eishorn** [Keriew/julius#20]
I encountered an issue that denying acceptance of any single type of good in a warehouse leads to this warehouse not accepting any imports at all. 

I first realized this playing through Mediolanum and Carthago with clay, then built up an "import wood - export furniture" test setup in Londinium: Wood is imported to my warehouses only as long as each and every good is set to accepting, whether it is importable/tradeable or not. Once i changed any setting in a warehouse, I have to delete and rebuild it to allow new imports. Traders will only sell goods to a warehouse which is accepting everything. Wood from sawmills will still be accepted.

I also built the main Julius branch by bvschaik where i could not reproduce the bug.

**Comment by LyonHe** [comment]
I believe the issue is due to change in src/figuretype/trader.c on Mar 10 commit 'Expand limits, change savegame extension #15'.
Line 270 in function 'get_closest_warehouse' was change from
`if (!building_warehouse_is_not_accepting(city_trade_next_caravan_import_resource(),b)) {`
to
`if (building_warehouse_is_not_accepting(city_trade_next_caravan_import_resource(),b)) {`
This causes the caravan traders to skip the trading resources.

**Comment by eishorn** [comment]
Changed the line and recompiled, warehouses are behaving as expected again so far.

Besides, I'd like to thank everybody putting effort into making Caesar 3 even better than it was before!

**Comment by Keriew** [comment]
Nice catch. That change was not intended.
