### ISSUE TITLE
Doesn't read save files.

### ISSUE THREAD

**Issue by shodmon** [Keriew/julius#4]

**Comment by Keriew** [comment]
Could you describe the problem more? Does it not read the original C3 saves? Julius saves?

If you add any roadblocks, Julius and the original C3 won't be able to open any saves from my fork, because of a reference to missing graphics and that's just unavoidable consequence. If you want to load your saves from GC, delete the roadblocks first. If it's a different problem, please explain more.

**Comment by shodmon** [comment]
I guess, the problem happened because my save files were in AppData folder (not in Program Files / C3). When I tried original Julius, save files _did_ read when they were in C3 (in Program Files) folder. Thank you. Please, delete this issue thread.

**Comment by shodmon** [comment]
I guess, the problem happened because my save files were in AppData folder (not in Program Files / C3). When I tried original Julius, save files did read when they were in C3 (in Program Files) folder. Thank you. Please, delete this issue thread.
